### ISSUE TITLE
Project isn't extendable

### ISSUE THREAD

**Issue by YegorZuev** [BlackPepperSoftware/bowman#11]
Currently it is too hard to make some custom extensions to modify behavior of client depending on some specific need. For example, to make some minor changes inside one of GetterSetterMethodHandler method's (which might be our project-specific) it is required to fully copy-paste the whole GetterSetterMethodHandler class and ClientProxyFactory class (due to everything is private). Moreover, it is possible only by creating package uk.co.blackpepper.bowman in our project due to (due to package access for classes).
What needs to be changed:
1. Make all classes public
2. Make most of (or almost all) private class fields (or getters for them) protected and most of (or almost all) private methods protected
3. Consider to simplify way to instantiate objects - reduce number of factories, builders etc.

**Comment by hdpe** [comment]
Hi, and thanks very much for your feedback! I'm very happy to open the API up where needed but, in my opinion, what you are proposing is just poor API design.

We're not at a 1.0 release, and I reserve the right to change the public API on minor version increments, but nevertheless I try not to without good reason, and haven't done so for a while. Making everything public/protected just means that the public API is *everything*, and makes it impossible to change anything without introducing a difficult upgrade path for existing clients. Generally in OO, encapsulation and information hiding are seen as good things! Carefully introducing extension points is IMHO hugely preferable to just making everything public. The factories are intended to help, rather than hinder this; if someone has a need, we can then just make them public and support their customisation in the configuration.

The API has been considered carefully, but it's definitely not perfect! I do feel your pain regarding not being able to customise it sufficiently - we've all been there. So what I'm particularly interested in is: what extension points do you feel you need in order to achieve what you want? You say your requirement is project-specific. That's fine: we can just introduce some means of customising the configuration, and this may then benefit other users. The long-term aim of this library is, I guess, to provide a generic, link-traversing, model-mapping client for any JSON+HAL API. If your use case fits that, I'm definitely interested in working with you to work out how it can help you.

**Comment by YegorZuev** [comment]
Hi there. 
Thank you for your response. I agree that this is quite double-edged: making classes public would imply them as a part of API, but leaving them package-level would forbid customization.
What we are currently doing in extensions:
For the start, adding Polymorphism support. We have hierarchy of resources and would like to work with parent interfaces. E.g. we have "Employee extends User" and "Customer extends User" - we want to get all users by calling "/users". The same for collection of linked resource - we don't want our user to have "billingAddresses", "shippingAddresses", "residenceAddresses" fields/links, but only one "addresses". And so on. This require some changes to serialization/deserialization in a really deep places of framework.
We are also more focused on our internal interface agreements for HAL API (powered by Spring Data Rest), rather that achieving universal HAL client, so for some conveniences we are also introducing (or might do it in the future) some changes on the server side. Thus, customization ability of client framework OR some king of custom implementation injections is what we are looking right now.

**Comment by hdpe** [comment]
To take one of your examples, I wonder if introducing features so that you could do:

```java
@LinkedResource(rels = {"billingAddresses", "shippingAddresses"})
public Collection<Address> getAddresses() { ... }
```

(just an idea - not a final/finished feature proposal!)

or perhaps:

```java
@LinkedResource(rel = "addresses", discriminator = YourBillingAddressDiscriminator.class)
public Address getBillingAddress() { ... }
```

would get you close to what you want? I would be very happy to see issues raised for this sort of missing functionality and would gladly consider PRs for this sort of thing. If you could raise specific issues addressing the gaps in the library's functionality that you've found, I'd be really grateful.

I think this is the way I'd like to see the library evolve, and that making `GetterSetterMethodHandler` public is just completely the wrong approach - this is just far too low-level an implementation detail and making it public will just make implementing features like this that much harder.

**Comment by YegorZuev** [comment]
Currently I have implemented one additional annotation to handle client side of class hierarchy:
`@RemoteResource("/users")
@Children({ Employee.class, Customer.class })
public abstract class User{
}`
It feels more convenient than adding "rels" to each LinkedResource because you can do it just in one place.
We will definitely consider creating a PR with changes we think should be really generic, but it would take some time due to current project plans. One hinder we have with this is we test it only on our Service implementation, so we are not aware if our changes fit for environment you're using and vise versa. 
p.s. by the way, regarding gaps in functionality - seems like getAll() returns only the first page of objects without pagination support. I will take a closer look at that soon.

**Comment by hdpe** [comment]
To contribute to the project, the only environment you need to be concerned with aligning to is that used by the project's [integration tests](https://github.com/BlackPepperSoftware/bowman/tree/master/test).

Thanks very much for the info. Please raise any further issues you have with the library (such as the getAll problem you mention) as separate issues so we can keep track of them. It would be great to have issues or preliminary PRs for e.g. the functionality exposed by your `@Children` annotation too if you get the time at any point.

**Comment by YegorZuev** [comment]
Hello @hdpe , 
Could you please provide me with pushing rights so I can make PR with the first portion of my changes?
Thank you in advance!

**Comment by hdpe** [comment]
Hi @YegorZuev - you don't need pushing rights. Please push your changes to a branch in your fork and raise a pull request from there for us to review.

https://help.github.com/articles/creating-a-pull-request/

Thanks

**Comment by YegorZuev** [comment]
Great, thank you, I have created PR from my fork https://github.com/BlackPepperSoftware/bowman/pull/12
