### ISSUE TITLE
Accessing abstract collection-valued @LinkedResources method throws NPE

### ISSUE THREAD

**Issue by hdpe** [BlackPepperSoftware/bowman#25]
As [reported](https://github.com/BlackPepperSoftware/bowman/issues/16#issuecomment-402008808) by @danapoklepovich, attempting to proxy a collection-valued method on an interface

```java
@LinkedResource
List<Thing> things();
```

throws an NPE due to being unable to access the initial collection by calling the original method, as we do for concrete types.

**Comment by hdpe** [comment]
As I say @danapoklepovich, I think your reasoning as to why this is happening is completely right.

I think we need to fall back to creating the collection via the 'new' (proxy) method's type when `originalMethod` is null.

Failing test added. If you want to have a look at this, and raise a PR if you can work it out, please do! Otherwise I will try to get a chance to pick this up myself soon.

**Comment by danapoklepovich** [comment]
Cheers for this! I'll give it a go but I do have limited experience so i'm not confident.

**Comment by danapoklepovich** [comment]
Hi @hdpe could you please review my PR, I can't add you as a reviewer because Coveralls isn't passing I think. However your IT should be hitting the sections of code that are being flagged as uncovered as I have tested this use case against my client app and run your IT and everything is working as expected. 
I really need this functionality pulled in, happy to write some unit tests if that is the problem but I can't see any similar examples in the unit tests written in your Test class.

**Comment by hdpe** [comment]
@danapoklepovich thanks very much for your PR! I really am very grateful. As I maintain this project largely in my free time, I can't always respond to issues and PRs immediately, but I will endeavour to do so as soon as possible.

On the unit test point - yes, these would be helpful - rightly or wrongly this area is currently covered by https://github.com/BlackPepperSoftware/bowman/blob/master/client/src/test/java/uk/co/blackpepper/bowman/JavassistClientProxyFactoryTest.java

I'll start reviewing the rest of your PR ASAP.

Thanks

**Comment by danapoklepovich** [comment]
@hdpe Not a problem mate, was more concerned that this wasn't what you were looking for. Happy to have a look over and see if I can write in some more tests. Thanks !
