### ISSUE TITLE
Changing the RestTemplate

### ISSUE THREAD

**Issue by flostadler** [BlackPepperSoftware/bowman#28]
I'd like to change the RestTemplate to a custom implementation of mine, but I only found a way to configure it using RestTemplateConfigurer.

Is there a way to accomplish this?

**Comment by hdpe** [comment]
The only supported way of modifying the `RestTemplate` at present is via the `RestTemplateConfigurer'.

It would be tricky to allow clients to inject their own `RestTemplate`, because the Bowman-internal one uses a specially configured `ObjectMapper` to support the creation of its proxies, and these proxies then need a reference back to the `RestTemplate` in order to retrieve linked resources. So there's a certain minimum configuration we have to make.

What specific configuration are you trying to achieve? By "custom implementation" of `RestTemplate`, do you mean you've subclassed this and would like to inject your version?

**Comment by flostadler** [comment]
I tried to add caching and retry functionality by decorating the bowman-internal `RestTemplate`.
Which worked like a charm, but without a setter for the `RestTemplate` i wasn't able to use it.

**Comment by hdpe** [comment]
Could you re-work your decorator functionality into a `ClientHttpRequestInterceptor`, and register this on the internal `RestTemplate`?

I think this is the intended way to implement cross-cutting interception on a `RestTemplate`. I'd imagine this would be easier, if only because it has such a huge API.

**Comment by flostadler** [comment]
That should work for our usecase,
thanks!
